# Generated by Django 5.2.6 on 2026-03-01 13:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VaultItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("secure_note", "Secure Note"),
                            ("card", "Card"),
                            ("identity", "Identity"),
                        ],
                        default="login",
                        max_length=20,
                    ),
                ),
                ("encrypted_name", models.TextField()),
                ("iv_name", models.CharField(max_length=32)),
                ("encrypted_data", models.TextField()),
                ("iv_data", models.CharField(max_length=32)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vault_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "vault_items",
            },
        ),
        migrations.CreateModel(
            name="VaultItemHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("encrypted_name", models.TextField()),
                ("iv_name", models.CharField(max_length=32)),
                ("encrypted_data", models.TextField()),
                ("iv_data", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vault_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="vault.vaultitem",
                    ),
                ),
            ],
            options={
                "db_table": "vault_item_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="vaultitem",
            index=models.Index(
                fields=["user", "is_deleted", "updated_at"],
                name="vault_items_user_id_cd5098_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vaultitemhistory",
            index=models.Index(
                fields=["vault_item", "created_at"],
                name="vault_item__vault_i_ddafb4_idx",
            ),
        ),
    ]
