# Generated by Django 5.1 on 2026-03-09 09:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="vaultitem",
            name="display_order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="vaultitem",
            name="is_favourite",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="vaultitem",
            index=models.Index(
                fields=["user", "is_favourite", "is_deleted"],
                name="vault_items_user_id_c0bfba_idx",
            ),
        ),
    ]
