# Generated by Django 5.1 on 2026-03-12 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0002_vaultitem_display_order_vaultitem_is_favourite_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vaultitem",
            old_name="encrypted_name",
            new_name="encrypted_meta",
        ),
        migrations.RenameField(
            model_name="vaultitem",
            old_name="iv_name",
            new_name="iv_meta",
        ),
        migrations.RenameField(
            model_name="vaultitemhistory",
            old_name="encrypted_name",
            new_name="encrypted_meta",
        ),
        migrations.RenameField(
            model_name="vaultitemhistory",
            old_name="iv_name",
            new_name="iv_meta",
        ),
    ]
